apiVersion: apps/v1
kind: Deployment
metadata:
  name: flexiloan-nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flexiloan-nodeapp
  template:
    metadata:
      labels:
        app: flexiloan-nodeapp
    spec:
      containers:
      - name: flexiloan-nodeapp
        image: pras1804/flexiloan:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: flexiloan-nodeapp-svc
spec:
  selector:
    app: flexiloan-nodeapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---

#HPA configuration
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flexiloan-nodeapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flexiloan-nodeapp
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
